package com.snb.ms.auth.authorization;

public enum Privileges {
  USER_VIEW,
  USER_MANAGE,
  ROLE_MANAGE,
  PRIVILEGE_MANAGE,
  COMPANY_VIEW,
  COMPANY_MANAGE,
  SALESMAN_VIEW,
  SALESMAN_MANAGE,
  REPORT_VIEW,
  ANNOUNCEMENT_VIEW,
  ANNOUNCEMENT_MANAGE,
  QUOTATION_VIEW,
  QUOTATION_MANAGE,
  USER_DEVICE_VIEW,
  USER_DEVICE_MANAGE,
  TIER_VIEW,
  TIER_MANAGE
}
