INSERT INTO USERS (
    EMAIL_ADDRESS,
    MOBILE_NUMBER,
    USER_TYPE,
    FAILED_ATTEMPTS,
    ACCOUNT_LOCKED_FLAG,
    LAST_LOGIN_AT,
    ACCOUNT_STATUS,
    CREATED_BY,
    CREATED_AT,
    UPDATED_BY,
    UPDATED_AT,
    DELETED_FLAG,
    DELETED_AT,
    VERSION_NUMBER
) VALUES (
    'admin1@snb.com',
    '971500000001',
    'ADMIN',
    0,
    'N',
    CURRENT_TIMESTAMP,
    'ACTIVE',
    1,
    CURRENT_TIMESTAMP,
    1,
    CURRENT_TIMESTAMP,
    'N',
    NULL,
    0
);

INSERT INTO ADMIN_USERS (
    USER_ID,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    EXTENSION_NUMBER,
    ADMIN_TYPE,
    ADMIN_STATUS,
    CREATED_BY,
    CREATED_AT,
    UPDATED_BY,
    UPDATED_AT,
    DELETED_FLAG,
    DELETED_AT,
    VERSION_NUMBER
) VALUES (
    (SELECT USER_ID FROM USERS WHERE EMAIL_ADDRESS = 'admin1@snb.com'),
    'System',
    'Core',
    'Administrator',
    '1001',
    'SUPER_ADMIN',
    'ACTIVE',
    1,
    CURRENT_TIMESTAMP,
    1,
    CURRENT_TIMESTAMP,
    'N',
    NULL,
    0
);

INSERT INTO USERS (
    EMAIL_ADDRESS,
    MOBILE_NUMBER,
    USER_TYPE,
    FAILED_ATTEMPTS,
    ACCOUNT_LOCKED_FLAG,
    LAST_LOGIN_AT,
    ACCOUNT_STATUS,
    CREATED_BY,
    CREATED_AT,
    UPDATED_BY,
    UPDATED_AT,
    DELETED_FLAG,
    DELETED_AT,
    VERSION_NUMBER
) VALUES (
    'company1@snb.com',
    '971500000101',
    'COMPANY',
    0,
    'N',
    CURRENT_TIMESTAMP,
    'ACTIVE',
    1,
    CURRENT_TIMESTAMP,
    1,
    CURRENT_TIMESTAMP,
    'N',
    NULL,
    0
);

INSERT INTO COMPANY (
    USER_ID,
    REGISTRATION_NUMBER,
    COMPANY_STATUS,
    COMPANY_TYPE,
    CREATED_BY,
    CREATED_AT,
    UPDATED_BY,
    UPDATED_AT,
    DELETED_FLAG,
    DELETED_AT,
    VERSION_NUMBER
) VALUES (
    (SELECT USER_ID FROM USERS WHERE EMAIL_ADDRESS = 'company1@snb.com'),
    'REG-100001',
    'ACTIVE',
    'LLC',
    1,
    CURRENT_TIMESTAMP,
    1,
    CURRENT_TIMESTAMP,
    'N',
    NULL,
    0
);

INSERT INTO USERS (
    EMAIL_ADDRESS,
    MOBILE_NUMBER,
    USER_TYPE,
    FAILED_ATTEMPTS,
    ACCOUNT_LOCKED_FLAG,
    LAST_LOGIN_AT,
    ACCOUNT_STATUS,
    CREATED_BY,
    CREATED_AT,
    UPDATED_BY,
    UPDATED_AT,
    DELETED_FLAG,
    DELETED_AT,
    VERSION_NUMBER
) VALUES (
    'salesman1@snb.com',
    '971500000201',
    'SALESMAN',
    0,
    'N',
    CURRENT_TIMESTAMP,
    'ACTIVE',
    1,
    CURRENT_TIMESTAMP,
    1,
    CURRENT_TIMESTAMP,
    'N',
    NULL,
    0
);

INSERT INTO SALESMAN (
    USER_ID,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    ACCOUNT_NUMBER,
    CIF_NUMBER,
    ID_NUMBER,
    AVAILABLE_INCENTIVE_AMOUNT,
    CREATED_BY,
    CREATED_AT,
    UPDATED_BY,
    UPDATED_AT,
    DELETED_FLAG,
    DELETED_AT,
    VERSION_NUMBER
) VALUES (
    (SELECT USER_ID FROM USERS WHERE EMAIL_ADDRESS = 'salesman1@snb.com'),
    'Aamir',
    'K',
    'Rahman',
    'ACCT-200001',
    'CIF-300001',
    'ID-400001',
    2500.00,
    1,
    CURRENT_TIMESTAMP,
    1,
    CURRENT_TIMESTAMP,
    'N',
    NULL,
    0
);

INSERT INTO COMPANY_SALESMAN (
    COMPANY_ID,
    SALESMAN_ID,
    CURRENT_TARGET,
    ACHIEVED_TARGET,
    ASSOCIATION_STATUS,
    JOINED_AT,
    EXITED_AT
) VALUES (
    (SELECT COMPANY_ID FROM COMPANY WHERE REGISTRATION_NUMBER = 'REG-100001'),
    (SELECT SALESMAN_ID FROM SALESMAN WHERE ACCOUNT_NUMBER = 'ACCT-200001'),
    100000.00,
    35000.00,
    'ACTIVE',
    CURRENT_TIMESTAMP,
    NULL
);

INSERT INTO USERS (
    EMAIL_ADDRESS,
    MOBILE_NUMBER,
    USER_TYPE,
    FAILED_ATTEMPTS,
    ACCOUNT_LOCKED_FLAG,
    LAST_LOGIN_AT,
    ACCOUNT_STATUS,
    CREATED_BY,
    CREATED_AT,
    UPDATED_BY,
    UPDATED_AT,
    DELETED_FLAG,
    DELETED_AT,
    VERSION_NUMBER
) VALUES (
    'admin2@snb.com',
    '971500000002',
    'ADMIN',
    0,
    'N',
    CURRENT_TIMESTAMP,
    'ACTIVE',
    1,
    CURRENT_TIMESTAMP,
    1,
    CURRENT_TIMESTAMP,
    'N',
    NULL,
    0
);

INSERT INTO ADMIN_USERS (
    USER_ID,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    EXTENSION_NUMBER,
    ADMIN_TYPE,
    ADMIN_STATUS,
    CREATED_BY,
    CREATED_AT,
    UPDATED_BY,
    UPDATED_AT,
    DELETED_FLAG,
    DELETED_AT,
    VERSION_NUMBER
) VALUES (
    (SELECT USER_ID FROM USERS WHERE EMAIL_ADDRESS = 'admin2@snb.com'),
    'Branch',
    'Operations',
    'Admin',
    '1002',
    'OPS_ADMIN',
    'ACTIVE',
    1,
    CURRENT_TIMESTAMP,
    1,
    CURRENT_TIMESTAMP,
    'N',
    NULL,
    0
);
