CREATE TABLE IF NOT EXISTS USERS (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    EMAIL_ADDRESS VARCHAR(150) NOT NULL,
    MOBILE_NUMBER VARCHAR(20) NOT NULL,
    PASSWORD_HASH VARCHAR(255),

    USER_TYPE VARCHAR(20),
    FAILED_ATTEMPTS INT DEFAULT 0,
    ACCOUNT_LOCKED_FLAG CHAR(1) DEFAULT 'N',
    LAST_LOGIN_AT TIMESTAMP,
    ACCOUNT_STATUS VARCHAR(20),

    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,
    DELETED_FLAG CHAR(1) DEFAULT 'N',
    DELETED_AT TIMESTAMP,
    VERSION_NUMBER BIGINT DEFAULT 0,

    CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL_ADDRESS),
    CONSTRAINT UK_USERS_MOBILE UNIQUE (MOBILE_NUMBER),

    CONSTRAINT CHK_USER_LOCKED CHECK (ACCOUNT_LOCKED_FLAG IN ('Y','N')),
    CONSTRAINT CHK_USER_DELETED CHECK (DELETED_FLAG IN ('Y','N'))
);

CREATE TABLE IF NOT EXISTS COMPANY (
    COMPANY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    USER_ID BIGINT NOT NULL,
    REGISTRATION_NUMBER VARCHAR(100) NOT NULL,
    COMPANY_STATUS VARCHAR(20),
    COMPANY_TYPE VARCHAR(50),

    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,
    DELETED_FLAG CHAR(1) DEFAULT 'N',
    DELETED_AT TIMESTAMP,
    VERSION_NUMBER BIGINT DEFAULT 0,

    CONSTRAINT UK_COMPANY_USER UNIQUE (USER_ID),
    CONSTRAINT UK_COMPANY_REG UNIQUE (REGISTRATION_NUMBER),

    CONSTRAINT FK_COMPANY_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_COMPANY_DELETED CHECK (DELETED_FLAG IN ('Y','N'))
);

CREATE TABLE IF NOT EXISTS SALESMAN (
    SALESMAN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    USER_ID BIGINT NOT NULL,

    FIRST_NAME VARCHAR(100),
    MIDDLE_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),

    ACCOUNT_NUMBER VARCHAR(50),
    CIF_NUMBER VARCHAR(50),
    ID_NUMBER VARCHAR(50),

    AVAILABLE_INCENTIVE_AMOUNT DECIMAL(15,2) DEFAULT 0,

    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,
    DELETED_FLAG CHAR(1) DEFAULT 'N',
    DELETED_AT TIMESTAMP,
    VERSION_NUMBER BIGINT DEFAULT 0,

    CONSTRAINT UK_SALESMAN_USER UNIQUE (USER_ID),
    CONSTRAINT UK_SALESMAN_ACC UNIQUE (ACCOUNT_NUMBER),
    CONSTRAINT UK_SALESMAN_CIF UNIQUE (CIF_NUMBER),
    CONSTRAINT UK_SALESMAN_ID UNIQUE (ID_NUMBER),

    CONSTRAINT FK_SALESMAN_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_SALESMAN_DELETED CHECK (DELETED_FLAG IN ('Y','N'))
);

CREATE TABLE IF NOT EXISTS COMPANY_SALESMAN (
    COMPANY_SALESMAN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    COMPANY_ID BIGINT NOT NULL,
    SALESMAN_ID BIGINT NOT NULL,

    CURRENT_TARGET DECIMAL(15,2),
    ACHIEVED_TARGET DECIMAL(15,2),

    ASSOCIATION_STATUS VARCHAR(20),
    JOINED_AT TIMESTAMP,
    EXITED_AT TIMESTAMP,

    CONSTRAINT FK_CS_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES COMPANY(COMPANY_ID),

    CONSTRAINT FK_CS_SALESMAN FOREIGN KEY (SALESMAN_ID)
        REFERENCES SALESMAN(SALESMAN_ID),

    CONSTRAINT UK_COMPANY_SALESMAN UNIQUE (COMPANY_ID, SALESMAN_ID)
);

CREATE TABLE IF NOT EXISTS COMPANY_SALESMAN_INVITATION (
    COMPANY_SALESMAN_INVITATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    SALESMAN_ID BIGINT,
    EMAIL_ADDRESS VARCHAR(150) NOT NULL,
    MOBILE_NUMBER VARCHAR(20) NOT NULL,
    ID_NUMBER VARCHAR(50) NOT NULL,
    COMPANY_ID BIGINT NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    INVITED_AT TIMESTAMP NOT NULL,
    RESPONDED_AT TIMESTAMP,
    EXPIRY_DATE TIMESTAMP NOT NULL,

    CONSTRAINT FK_CSI_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES COMPANY(COMPANY_ID),

    CONSTRAINT FK_CSI_SALESMAN FOREIGN KEY (SALESMAN_ID)
        REFERENCES SALESMAN(SALESMAN_ID)
);

CREATE TABLE IF NOT EXISTS ADMIN_USERS (
    ADMIN_USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    USER_ID BIGINT NOT NULL,

    FIRST_NAME VARCHAR(100),
    MIDDLE_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),

    EXTENSION_NUMBER VARCHAR(20),
    SNB_ID VARCHAR(50) NOT NULL,
    ADMIN_STATUS VARCHAR(20),

    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,

    DELETED_FLAG CHAR(1) DEFAULT 'N',
    DELETED_AT TIMESTAMP,

    VERSION_NUMBER BIGINT DEFAULT 0,

    CONSTRAINT UK_ADMIN_USER UNIQUE (USER_ID),
    CONSTRAINT UK_ADMIN_USER_SNB_ID UNIQUE (SNB_ID),

    CONSTRAINT FK_ADMIN_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_ADMIN_DELETED_FLAG CHECK (DELETED_FLAG IN ('Y','N')),

    CONSTRAINT CHK_ADMIN_STATUS CHECK (ADMIN_STATUS IN ('ACTIVE','INACTIVE','SUSPENDED'))
);

CREATE TABLE IF NOT EXISTS ANNOUNCEMENT (
    ANNOUNCEMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    TITLE VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(2000) NOT NULL,
    IMAGE_URL VARCHAR(500),
    PRIORITY VARCHAR(20) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    ACTION_URL VARCHAR(500),

    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,
    DELETED_FLAG CHAR(1) DEFAULT 'N',
    DELETED_AT TIMESTAMP,
    VERSION_NUMBER BIGINT DEFAULT 0,

    CONSTRAINT CHK_ANNOUNCEMENT_PRIORITY CHECK (PRIORITY IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    CONSTRAINT CHK_ANNOUNCEMENT_TYPE CHECK (TYPE IN ('GENERAL','INCENTIVE','CAMPAIGN','NEWS','MAGAZINE')),
    CONSTRAINT CHK_ANNOUNCEMENT_STATUS CHECK (STATUS IN ('DRAFT','PUBLISHED','ARCHIVED')),
    CONSTRAINT CHK_ANNOUNCEMENT_DELETED CHECK (DELETED_FLAG IN ('Y','N'))
);

CREATE TABLE IF NOT EXISTS QUOTATION (
    QUOTATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    QUOTATION_NO VARCHAR(100) NOT NULL,
    COMPANY_ID BIGINT NOT NULL,
    SALESMAN_ID BIGINT NOT NULL,
    CUSTOMER_NATIONAL_ID VARCHAR(50) NOT NULL,
    CUSTOMER_MOBILE VARCHAR(20) NOT NULL,
    CUSTOMER_EMAIL VARCHAR(150) NOT NULL,
    VEHICLE_ID BIGINT NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    VEHICLE_PRICE DECIMAL(15,2) NOT NULL,
    DOWN_PAYMENT DECIMAL(15,2) NOT NULL,
    LEASE_TENURE_MONTHS INT NOT NULL,
    MONTHLY_INSTALLMENT DECIMAL(15,2) NOT NULL,
    TOTAL_QUOTAION_AMOUNT DECIMAL(15,2) NOT NULL,
    IS_INCENTIVE_ELIGIBLE BOOLEAN NOT NULL,
    INCENTIVE_CAMPAIGN_ID BIGINT,
    VALID_FROM DATE NOT NULL,
    VALID_UNTIL DATE NOT NULL,

    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,
    DELETED_FLAG CHAR(1) DEFAULT 'N',
    DELETED_AT TIMESTAMP,
    VERSION_NUMBER BIGINT DEFAULT 0,

    CONSTRAINT UK_QUOTATION_NO UNIQUE (QUOTATION_NO),

    CONSTRAINT FK_QUOTATION_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES COMPANY(COMPANY_ID),

    CONSTRAINT FK_QUOTATION_SALESMAN FOREIGN KEY (SALESMAN_ID)
        REFERENCES SALESMAN(SALESMAN_ID),

    CONSTRAINT CHK_QUOTATION_DELETED CHECK (DELETED_FLAG IN ('Y','N'))
);

CREATE TABLE IF NOT EXISTS USER_DEVICE (
    USER_DEVICE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    USER_ID BIGINT NOT NULL,
    DEVICE_ID VARCHAR(100) NOT NULL,
    DEVICE_TYPE VARCHAR(50) NOT NULL,
    DEVICE_MODEL VARCHAR(100),
    OS_VERSION VARCHAR(50),
    APP_VERSION VARCHAR(50),
    PUSH_TOKEN VARCHAR(500),
    PUSH_TOKEN_UPDATED_AT TIMESTAMP,
    STATUS VARCHAR(30) NOT NULL,
    REGISTERED_AT TIMESTAMP NOT NULL,
    LAST_ACTIVE_AT TIMESTAMP NOT NULL,
    LAST_LOGIN_AT TIMESTAMP NOT NULL,
    IP_ADDRESS VARCHAR(45),
    LOCATION VARCHAR(255),
    IS_TRUSTED BOOLEAN,
    FAILED_ATTEMPTS INT DEFAULT 0,
    DEVICE_NAME VARCHAR(100),
    NOTIFICATIONS_ENABLED BOOLEAN NOT NULL,

    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,
    DELETED_FLAG CHAR(1) DEFAULT 'N',
    DELETED_AT TIMESTAMP,
    VERSION_NUMBER BIGINT DEFAULT 0,

    CONSTRAINT UK_USER_DEVICE_DEVICE_ID UNIQUE (DEVICE_ID),

    CONSTRAINT FK_USER_DEVICE_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_USER_DEVICE_DELETED CHECK (DELETED_FLAG IN ('Y','N'))
);

CREATE TABLE IF NOT EXISTS TIER (
    TIER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    TIER_CODE VARCHAR(50) NOT NULL,
    TIER_NAME VARCHAR(150) NOT NULL,
    MIN_ACHIEVEMENT_PERCENTAGE DECIMAL(9,2) NOT NULL,
    MAX_ACHIEVEMENT_PERCENTAGE DECIMAL(9,2) NOT NULL,
    INCENTIVE_TYPE VARCHAR(50) NOT NULL,
    INCENTIVE_VALUE DECIMAL(15,2) NOT NULL,
    DISPLAY_ORDER INT NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL,
    EFFECTIVE_TO DATE NOT NULL,

    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,
    DELETED_FLAG CHAR(1) DEFAULT 'N',
    DELETED_AT TIMESTAMP,
    VERSION_NUMBER BIGINT DEFAULT 0,

    CONSTRAINT UK_TIER_CODE UNIQUE (TIER_CODE),
    CONSTRAINT CHK_TIER_DELETED CHECK (DELETED_FLAG IN ('Y','N'))
);

CREATE TABLE IF NOT EXISTS ROLE (
    ROLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    ROLE_CODE VARCHAR(100) NOT NULL,
    ROLE_NAME VARCHAR(150) NOT NULL,
    DESCRIPTION VARCHAR(255),

    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,
    DELETED_FLAG CHAR(1) DEFAULT 'N',
    DELETED_AT TIMESTAMP,
    VERSION_NUMBER BIGINT DEFAULT 0,

    CONSTRAINT UK_ROLE_CODE UNIQUE (ROLE_CODE),
    CONSTRAINT UK_ROLE_NAME UNIQUE (ROLE_NAME),

    CONSTRAINT CHK_ROLE_DELETED CHECK (DELETED_FLAG IN ('Y','N'))
);

CREATE TABLE IF NOT EXISTS PRIVILEGE (
    PRIVILEGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    PRIVILEGE_CODE VARCHAR(100) NOT NULL,
    PRIVILEGE_NAME VARCHAR(150) NOT NULL,
    DESCRIPTION VARCHAR(255),

    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,
    DELETED_FLAG CHAR(1) DEFAULT 'N',
    DELETED_AT TIMESTAMP,
    VERSION_NUMBER BIGINT DEFAULT 0,

    CONSTRAINT UK_PRIVILEGE_CODE UNIQUE (PRIVILEGE_CODE),
    CONSTRAINT UK_PRIVILEGE_NAME UNIQUE (PRIVILEGE_NAME),

    CONSTRAINT CHK_PRIVILEGE_DELETED CHECK (DELETED_FLAG IN ('Y','N'))
);

CREATE TABLE IF NOT EXISTS USER_ROLE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,

    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,
    DELETED_FLAG CHAR(1) DEFAULT 'N',
    DELETED_AT TIMESTAMP,
    VERSION_NUMBER BIGINT DEFAULT 0,

    CONSTRAINT UK_USER_ROLE UNIQUE (USER_ID, ROLE_ID),

    CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES ROLE(ROLE_ID),

    CONSTRAINT CHK_USER_ROLE_DELETED CHECK (DELETED_FLAG IN ('Y','N'))
);

CREATE TABLE IF NOT EXISTS ROLE_PRIVILEGE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    ROLE_ID BIGINT NOT NULL,
    PRIVILEGE_ID BIGINT NOT NULL,

    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,
    DELETED_FLAG CHAR(1) DEFAULT 'N',
    DELETED_AT TIMESTAMP,
    VERSION_NUMBER BIGINT DEFAULT 0,

    CONSTRAINT UK_ROLE_PRIVILEGE UNIQUE (ROLE_ID, PRIVILEGE_ID),

    CONSTRAINT FK_ROLE_PRIVILEGE_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES ROLE(ROLE_ID),

    CONSTRAINT FK_ROLE_PRIVILEGE_PRIVILEGE FOREIGN KEY (PRIVILEGE_ID)
        REFERENCES PRIVILEGE(PRIVILEGE_ID),

    CONSTRAINT CHK_ROLE_PRIVILEGE_DELETED CHECK (DELETED_FLAG IN ('Y','N'))
);

ALTER TABLE USERS ALTER COLUMN USER_ID RESTART WITH 1001;
ALTER TABLE COMPANY ALTER COLUMN COMPANY_ID RESTART WITH 1001;
ALTER TABLE SALESMAN ALTER COLUMN SALESMAN_ID RESTART WITH 1001;
ALTER TABLE COMPANY_SALESMAN ALTER COLUMN COMPANY_SALESMAN_ID RESTART WITH 1001;
ALTER TABLE COMPANY_SALESMAN_INVITATION ALTER COLUMN COMPANY_SALESMAN_INVITATION_ID RESTART WITH 1001;
ALTER TABLE ADMIN_USERS ALTER COLUMN ADMIN_USER_ID RESTART WITH 1001;
ALTER TABLE ANNOUNCEMENT ALTER COLUMN ANNOUNCEMENT_ID RESTART WITH 1001;
ALTER TABLE QUOTATION ALTER COLUMN QUOTATION_ID RESTART WITH 1001;
ALTER TABLE USER_DEVICE ALTER COLUMN USER_DEVICE_ID RESTART WITH 1001;
ALTER TABLE TIER ALTER COLUMN TIER_ID RESTART WITH 1001;
ALTER TABLE ROLE ALTER COLUMN ROLE_ID RESTART WITH 1001;
ALTER TABLE PRIVILEGE ALTER COLUMN PRIVILEGE_ID RESTART WITH 1001;
ALTER TABLE USER_ROLE ALTER COLUMN ID RESTART WITH 1001;
ALTER TABLE ROLE_PRIVILEGE ALTER COLUMN ID RESTART WITH 1001;
