CREATE TABLE IF NOT EXISTS USERS (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    EMAIL_ADDRESS VARCHAR(150) NOT NULL,
    MOBILE_NUMBER VARCHAR(20) NOT NULL,

    USER_TYPE VARCHAR(20),
    FAILED_ATTEMPTS INT DEFAULT 0,
    ACCOUNT_LOCKED_FLAG CHAR(1) DEFAULT 'N',
    LAST_LOGIN_AT TIMESTAMP,
    ACCOUNT_STATUS VARCHAR(20),

    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,
    DELETED_FLAG CHAR(1) DEFAULT 'N',
    DELETED_AT TIMESTAMP,
    VERSION_NUMBER BIGINT DEFAULT 0,

    CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL_ADDRESS),
    CONSTRAINT UK_USERS_MOBILE UNIQUE (MOBILE_NUMBER),

    CONSTRAINT CHK_USER_LOCKED CHECK (ACCOUNT_LOCKED_FLAG IN ('Y','N')),
    CONSTRAINT CHK_USER_DELETED CHECK (DELETED_FLAG IN ('Y','N'))
);

CREATE TABLE IF NOT EXISTS COMPANY (
    COMPANY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    USER_ID BIGINT NOT NULL,
    REGISTRATION_NUMBER VARCHAR(100) NOT NULL,
    COMPANY_STATUS VARCHAR(20),
    COMPANY_TYPE VARCHAR(50),

    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,
    DELETED_FLAG CHAR(1) DEFAULT 'N',
    DELETED_AT TIMESTAMP,
    VERSION_NUMBER BIGINT DEFAULT 0,

    CONSTRAINT UK_COMPANY_USER UNIQUE (USER_ID),
    CONSTRAINT UK_COMPANY_REG UNIQUE (REGISTRATION_NUMBER),

    CONSTRAINT FK_COMPANY_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_COMPANY_DELETED CHECK (DELETED_FLAG IN ('Y','N'))
);

CREATE TABLE IF NOT EXISTS SALESMAN (
    SALESMAN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    USER_ID BIGINT NOT NULL,

    FIRST_NAME VARCHAR(100),
    MIDDLE_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),

    ACCOUNT_NUMBER VARCHAR(50),
    CIF_NUMBER VARCHAR(50),
    ID_NUMBER VARCHAR(50),

    AVAILABLE_INCENTIVE_AMOUNT DECIMAL(15,2) DEFAULT 0,

    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,
    DELETED_FLAG CHAR(1) DEFAULT 'N',
    DELETED_AT TIMESTAMP,
    VERSION_NUMBER BIGINT DEFAULT 0,

    CONSTRAINT UK_SALESMAN_USER UNIQUE (USER_ID),
    CONSTRAINT UK_SALESMAN_ACC UNIQUE (ACCOUNT_NUMBER),
    CONSTRAINT UK_SALESMAN_CIF UNIQUE (CIF_NUMBER),
    CONSTRAINT UK_SALESMAN_ID UNIQUE (ID_NUMBER),

    CONSTRAINT FK_SALESMAN_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_SALESMAN_DELETED CHECK (DELETED_FLAG IN ('Y','N'))
);

CREATE TABLE IF NOT EXISTS COMPANY_SALESMAN (
    COMPANY_SALESMAN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    COMPANY_ID BIGINT NOT NULL,
    SALESMAN_ID BIGINT NOT NULL,

    CURRENT_TARGET DECIMAL(15,2),
    ACHIEVED_TARGET DECIMAL(15,2),

    ASSOCIATION_STATUS VARCHAR(20),
    JOINED_AT TIMESTAMP,
    EXITED_AT TIMESTAMP,

    CONSTRAINT FK_CS_COMPANY FOREIGN KEY (COMPANY_ID)
        REFERENCES COMPANY(COMPANY_ID),

    CONSTRAINT FK_CS_SALESMAN FOREIGN KEY (SALESMAN_ID)
        REFERENCES SALESMAN(SALESMAN_ID),

    CONSTRAINT UK_COMPANY_SALESMAN UNIQUE (COMPANY_ID, SALESMAN_ID)
);

CREATE TABLE IF NOT EXISTS ADMIN_USERS (
    ADMIN_USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    USER_ID BIGINT NOT NULL,

    FIRST_NAME VARCHAR(100),
    MIDDLE_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),

    EXTENSION_NUMBER VARCHAR(20),

    ADMIN_TYPE VARCHAR(30),
    ADMIN_STATUS VARCHAR(20),

    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,

    DELETED_FLAG CHAR(1) DEFAULT 'N',
    DELETED_AT TIMESTAMP,

    VERSION_NUMBER BIGINT DEFAULT 0,

    CONSTRAINT UK_ADMIN_USER UNIQUE (USER_ID),

    CONSTRAINT FK_ADMIN_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_ADMIN_DELETED_FLAG CHECK (DELETED_FLAG IN ('Y','N')),

    CONSTRAINT CHK_ADMIN_STATUS CHECK (ADMIN_STATUS IN ('ACTIVE','INACTIVE','SUSPENDED'))
);
